server:
  port: 8889
management:
  endpoints:
    web:
      exposure:
        include: info, refresh
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck: true
    serverUrl:
      defaultZone: http://localhost:6206/eureka
