## Server
server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-exception: false
    include-message: never
    include-stacktrace: never
##Spring
spring:
  profiles: production
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      connection-init-sql: SELECT 1247 FROM DUAL
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        show-sql: true
    repositories:
      enabled: true
      open-in-view: true
      output: ##CMDLN
        ansi:
          enabled: always
  logging: ##LOGGING
    level:
      root: info
      sql: debug
      swagger: info
    charset:
      console: UTF-8
      file: UTF-8
    file:
      name: ./logs/out.log
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher

CONSTANTS:
  PROJECT_NAME: "SPRING_BASE"
    EXCLUDE_API_PATHS: "user," ## delimiter ','  no space around ','
    SALT_VALUE:
    ACCESS_TOKEN_NAME:
    ACCESS_TOKEN_TIME: 144  # minutes*hour
    REFRESH_SALT_VALUE:
    REFRESH_TOKEN_NAME:
    IS_DEV_MODE: false
    IMAGE_URL:
    FILE_PATH:
    RESIZE: "false"
    FILE_MAXIMUM_SIZE: "512" ##MB

  TEST:
    ACCESS_TOKEN: "Bearer eyJ0eXAiOiJyZiIsImFsZyI6IkhTNTEyIn0.eyJ1c2VyTm8iOjEsImlzcyI6IlNQUklOR19CQVNFIiwiaWF0IjoxNjU0Nzc2NDMxfQ.zFQrdsMMqK-MlVkHovH2XXE7T6-1U_ihSAa_XX6gAR2UANUFeD7jXPb-ruWS2K5wwvVEthEQlVZQGP8BF9v1OQ"
    REFRESH_TOKEN: "Bearer eyJ0eXAiOiJhYyIsImFsZyI6IkhTNTEyIn0.eyJ1c2VyTnVtIjoiMDEwMTIzNDEyMzQiLCJ1c2VyU3RhdHVzIjoiQUNUSVZBVEVEIiwidXNlck5vIjoxLCJpc3MiOiJTUFJJTkdfQkFTRSIsInVzZXJOYW1lIjoidGVzdDEiLCJleHAiOjE2NTQ5NzA2ODQsInVzZXJJZCI6InRlc3QxMiIsImlhdCI6MTY1NDkyNzQ4NH0.qHuWGEvWx2q971n-6oGEY6NeiTFj_crm3H-UPntLpliCXdM15G3z_Di7Td6PgH81ZJV4MfSxMUf6iolj0fqv7A"
    PREFIX: "http://localhost:8080/api"


